#!/bin/bash

INFO=$(acpi)

STATE=$(echo "$INFO" | grep -o "Charging")
LEVEL_PRCNTS=$(echo "$INFO" | grep -o '[0-9]\+%')
LEVEL=${LEVEL_PRCNTS:: -1}

MAIN_COLOR="#74AEAB"
ICON_COLOR=$MAIN_COLOR

if [[ "$LEVEL" > 80 ]]; then ICON=""
elif [[ "$LEVEL" > 60 &&  "$LEVEL" < 80 ]]; then ICON=""
elif [[ "$LEVEL" > 40 &&  "$LEVEL" < 60 ]]; then ICON=""
elif [[ "$LEVEL" > 20 &&  "$LEVEL" < 40 ]]; then ICON=""
elif [[ "$LEVEL" < 20 ]]; then
    ICON=""
    ICON_COLOR="red"
fi

if [[ "$(echo "$INFO" | grep -o "Charging")" ]]; then ICON_COLOR="green"; fi

if [[ "$BLOCK_BUTTON" == 1 ]]; then TEXT="<span color='$MAIN_COLOR'>$LEVEL_PRCNTS</span>"; fi

echo "<span color='$ICON_COLOR'>$ICON</span> "$TEXT
